import type {Subject} from "~/data/subject";

export const SubjectService = {
    getSubjects(): Subject[] {

        return [
            {
                "id": "01J9DYT0SED3210GEGKQX7V6CT",
                "name": "Profesinė anglų kalba",
                "semester": 1,
                "credits": 6,
                "evaluationForm": "E",
                "category": "1. Bendrieji koleginių studijų dalykai (moduliai)",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 36,
                "practiceHours": 54,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 66,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SKEGRK3RHQFFVJPZFG",
                "name": "Specialybės kalba",
                "semester": 1,
                "credits": 6,
                "evaluationForm": "E",
                "category": "1. Bendrieji koleginių studijų dalykai (moduliai)",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 18,
                "practiceHours": 18,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 66,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SM9S0KTFA02FC0FZYE",
                "name": "Vadyba",
                "semester": 3,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "1. Bendrieji koleginių studijų dalykai (moduliai)",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 16,
                "practiceHours": 16,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 46,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SMSJCZ60QNQTD1P6C9",
                "name": "Aplinkos ir žmonių sauga",
                "semester": 2,
                "credits": 6,
                "evaluationForm": "E",
                "category": "1. Bendrieji koleginių studijų dalykai (moduliai)",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 16,
                "practiceHours": 16,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 60,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SNXG652YPDBK5007S3",
                "name": "Sociologija",
                "semester": 4,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "1. Bendrieji koleginių studijų dalykai (moduliai)",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 16,
                "practiceHours": 16,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 46,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SPE87EJN5DJGK0DVQP",
                "name": "Ekonomika",
                "semester": 5,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "1. Bendrieji koleginių studijų dalykai (moduliai)",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 16,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SPZ1NF6YN7CWS2YE68",
                "name": "Teisė",
                "semester": 3,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "1. Bendrieji koleginių studijų dalykai (moduliai)",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 16,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SQG6EEZA2HKPRHNQW3",
                "name": "Operacinės sistemos",
                "semester": 1,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 54,
                "practiceHours": 36,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 76,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SQZ4HSCS2M57ABWXTQ",
                "name": "Matematika",
                "semester": 1,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 54,
                "practiceHours": 36,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 66,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SRG0EPW58K52WYRZJY",
                "name": "Struktūrinis programavimas",
                "semester": 1,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 36,
                "practiceHours": 54,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 66,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SRQXQ2FVQ7RKMSYQ7X",
                "name": "Informatikos įvadas",
                "semester": 1,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 36,
                "practiceHours": 36,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 16,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SSC07FZ8QCP91W6AEY",
                "name": "Tikimybių teorija ir matematinė statistika",
                "semester": 2,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 16,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SSV5TSA8ETGHWSGB6E",
                "name": "Algoritmai ir duomenų struktūros",
                "semester": 2,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 60,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0STJ61K8H5DT5348R4W",
                "name": "Diskrečioji matematika",
                "semester": 2,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 14,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0STKFCH295BZHRN6S56",
                "name": "Žmogaus ir kompiuterio sąveikos projektavimas",
                "semester": 2,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 70,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SV0YR5XADS7VTR1AMQ",
                "name": "Kompiuterinė grafika",
                "semester": 2,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 76,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SVVMR75Z1RMYZ847S7",
                "name": "Skaitiniai ir optimizavimo metodai",
                "semester": 3,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 76,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SW21K2EPQRJAE1N9FD",
                "name": "Duomenų bazių projektavimas",
                "semester": 3,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 86,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SX0CHN4EZS1FHD91D4",
                "name": "Informacijos sistemos",
                "semester": 3,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 14,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SY3CG0VANA21ST48F8",
                "name": "Objektinis programavimas",
                "semester": 3,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 60,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SYBD9T915ZWDV4D8NY",
                "name": "Verslo valdymo sistemos",
                "semester": 4,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 14,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SZ81WJRXXW5SKJSZW8",
                "name": "Daugiagijis programavimas",
                "semester": 4,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 14,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0SZ9ZM2HH1GZNB3B8GM",
                "name": "Kompiuteriai ir jų tinklai",
                "semester": 4,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 86,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TDJ9S8Y1RNBGR7RG4M",
                "name": "Baigiamasis darbas",
                "semester": 7,
                "credits": 15,
                "evaluationForm": "BD",
                "category": "2.4. Baigiamasis vertinimas",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 0,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 378,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T0VJHBMYW5H8RKEY3Y",
                "name": "Saityno paslaugos",
                "semester": 4,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 60,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T1SBYMDGQ3XHKE2Z2Y",
                "name": "Programų sistemų testavimas",
                "semester": 5,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 16,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T1X6X8XKGFR5YGJF33",
                "name": "Informacijos saugumas",
                "semester": 4,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 60,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T25D1W12ZW3ZCXMM9M",
                "name": "Intelektika",
                "semester": 6,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 36,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 72,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T26SG0QHF59BBM6ABY",
                "name": "Programų sistemų inžinerija",
                "semester": 5,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 32,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 24,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T3EPVZ6125VAFGVS25",
                "name": "Programinės įrangos kūrimo valdymas",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2. Studijų krypties dalykai (moduliai)",
                "categoryDescription": "2.1. Privalomi dalykai (moduliai)",
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 36,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 28,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T4BGFG87EPA6QVQ8GS",
                "name": "Duomenų tyryba",
                "semester": 5,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.1. Specializacija -………………….",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 76,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T4SMF72RNTCPQ2M5BB",
                "name": "Duomenų bazių valdymo sistemos",
                "semester": 5,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.1. Specializacija -………………….",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 60,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T51G10X48DFWJC9NWY",
                "name": "Nereliacinės duomenų bazės",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.1. Specializacija -………………….",
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 24,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T59FSY1A31HM444M45",
                "name": "Duomenų bazių serverių administravimas",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.1. Specializacija -………………….",
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 24,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T6GQTDXNXQNM841G2J",
                "name": "Mobiliosios programėlės",
                "semester": 5,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.2. Specializacija - ……………",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 60,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T6R8BFJ0CZ8B63PGJE",
                "name": "Hibridinės mobiliosios programėlės",
                "semester": 5,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.2. Specializacija - ……………",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 76,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T713DJEA9ED8S95SFW",
                "name": "Daiktų internetas",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.2. Specializacija - ……………",
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 24,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T7GXS1Z89VS13XPF6V",
                "name": "Išmaniųjų įrenginių komponentų programavimas",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.2. Specializacija - ……………",
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 24,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T839DB2840RWJYDP4H",
                "name": "Interneto svetainių serverio dalies kūrimas",
                "semester": 5,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.3. Specializacija ………………..",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 60,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T8Z8KHF4A9MAHYXY5V",
                "name": "Interneto svetainių kliento dalies kūrimas",
                "semester": 5,
                "credits": 6,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.3. Specializacija ………………..",
                "subjectType": 1,
                "lectureHours": 48,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 76,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T91B9E2A2SFD65JA9Y",
                "name": "Svetainių optimizacija paieškos sistemoms",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.3. Specializacija ………………..",
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 24,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0T91PR5C4TXNB8KTQNQ",
                "name": "Saityno saugumas",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "E",
                "category": "2.2. Specializacijos",
                "categoryDescription": "2.2.3. Specializacija ………………..",
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 24,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TASPZA3S47M221VZV2",
                "name": "Pirmoji programavimo praktika",
                "semester": 2,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "2.3. Praktikos",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 0,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 40,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TAZC7C5WP6TK19S7D2",
                "name": "Antroji programavimo praktika",
                "semester": 3,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "2.3. Praktikos",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 0,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 40,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TB1D6AZA0A4AC9HC7Y",
                "name": "Duomenų bazių praktika",
                "semester": 4,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "2.3. Praktikos",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 0,
                "practiceHours": 48,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 40,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TBA18ESJH75GZPC0QH",
                "name": "Profesinė praktika",
                "semester": 6,
                "credits": 12,
                "evaluationForm": "SP",
                "category": "2.3. Praktikos",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 0,
                "practiceHours": 192,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 140,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TCP9EQ0ZEHPMAVF0VM",
                "name": "Baigiamoji praktika",
                "semester": 7,
                "credits": 15,
                "evaluationForm": "SP",
                "category": "2.3. Praktikos",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 0,
                "practiceHours": 240,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 150,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TDDY5Z301V0ZKCJPN6",
                "name": "Programavimo kalba Java LPD",
                "semester": 5,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "3. Laisvai pasirenkamieji dalykai",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 16,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TEHP2JSY8D6MG0VCHP",
                "name": "Programavimo kalba C# LPD",
                "semester": 5,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "3. Laisvai pasirenkamieji dalykai",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 16,
                "practiceHours": 32,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TEKEBVCATYSCEYTXXE",
                "name": "Programavimo kalba Python LPD",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "3. Laisvai pasirenkamieji dalykai",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 24,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            },
            {
                "id": "01J9DYT0TF9VAZEET1CT30M8KG",
                "name": "3D grafika LPD",
                "semester": 6,
                "credits": 3,
                "evaluationForm": "SP",
                "category": "3. Laisvai pasirenkamieji dalykai",
                "categoryDescription": null,
                "subjectType": 1,
                "lectureHours": 24,
                "practiceHours": 24,
                "remoteLectureHours": 0,
                "remotePracticeHours": 0,
                "selfStudyHours": 30,
                "notes": "",
                "subGroupsCount": 1,
                "lecturesCount": 0,
                "finalProjectExamCount": 0,
                "otherContactHoursCount": 0,
                "consultationCount": 0,
                "gradingNumberCount": 0,
                "gradingHoursCount": null,
                "homeworkHoursCount": 0,
                "practiceReportHoursCount": 0,
                "remoteTeachingHoursCount": 0,
                "courseWorkHoursCount": 0,
                "examHours": 0,
                "otherNonContactCount": 0,
                "studyProgramId": "01J9DYQEJX9DHTHTPM9S02X94V",
                "studyProgram": null,
                "departmentId": null,
                "department": null,
                "lecturers": []
            }
        ]
    }
};

